server:
  service:
    type: LoadBalancer
    port: 443

applications:
  - name: example-app
    namespace: dev
    project: default
    source:
      repoURL: https://github.com/whitcr/example-app.git
      targetRevision: main
      path: helm-chart
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/whitcr/example-app.git
    type: git
    username: whitcr
    password: Dori22Woj


repoConfig:
  insecure: "true"