image:
  repository: 365528424244.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

config:
	POSTGRES_HOST: db
	POSTGRES_PORT: 5432
	POSTGRES_USER: user
	POSTGRES_DB: mydb
	POSTGRES_PASSWORD: pass
